---

- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "defaults.yml"

# @see https://osric.com/chris/accidental-developer/2017/10/ipa-server-upgrade-ipv6-stack-is-enabled-in-the-kernel-but-there-is-no-interface-that-has-1-address-assigned/
- name: Ensure IPv6 is ENABLED for CentOS7
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items :
    - name: net.ipv6.conf.all.disable_ipv6
      value: 0
    - name: net.ipv6.conf.lo.disable_ipv6
      value: 0
    - name: net.ipv6.conf.eth0.disable_ipv6
      value: 1
  become : True
  when: ansible_distribution =='CentOS' and ansible_distribution_major_version == '7'


- name: Install IPA Server Packages
  action: >
    {{ ansible_pkg_mgr }} name="{{ item }}" state=latest
  with_items: "{{ ipaserver_packages }}"
  become: True

- name: Free-up modnss TCP port
  include: modssl_config.yml

- name: Ubuntu fixes
  include: pam_sssd_config.yml
  when: ansible_os_family == 'Debian'

- name: Install IPA Server
  include: ipainstall.yml

- name: Start IPA Server
  include: ipastart.yml

- name: check for TGT and Kinit
  include: kinit.yml

- name: Generate HTTP Keytab for IPA Web Server
  include: ipahttp.yml
